# Generated by Django 3.1.5 on 2021-01-26 11:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('title', models.CharField(help_text='Title', max_length=50, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(help_text='Content', verbose_name='Content')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_article_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_article_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Data created on', verbose_name='Created on')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Data modified on', verbose_name='Modified by')),
                ('mode', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Trash', 'Trash')], default='Active', max_length=30, verbose_name='Mode')),
                ('text', models.CharField(help_text='Title', max_length=200, verbose_name='Comment Text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.article', verbose_name='Article')),
                ('created_by', models.ForeignKey(editable=False, help_text='Data created by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Data modified by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_app_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
